
SELECT 
MAX(IF(OCCUPATION = 'DOCTOR',NAME, NULL)) AS DOCTOR,
min(IF(OCCUPATION ='PROFESSOR',NAME, NULL)) AS PROFESSOR,
MIN(IF(OCCUPATION = 'SINGER',NAME, NULL)) AS SINGER,
max(IF(OCCUPATION = 'ACTOR',NAME, NULL)) AS ACTOR
FROM 
(SELECT NAME, OCCUPATION, Row_number() Over(PARTITION BY occupation ORDER BY name)as row_num FROM occupations) as ord group by row_num